version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: example_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"